services:
  api:
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:17
    hostname: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=bank
    ports:
      - "5432:5432"